// <auto-generated />
using Gunner.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gunner.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250505123109_CreateProductsTable")]
    partial class CreateProductsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gunner.Models.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("Gunner.Models.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            Brand = "Nike",
                            Description = "Official Arsenal FC jersey for the 2023 season.",
                            ListPrice = 90.0,
                            Price = 75.0,
                            Price100 = 65.0,
                            Price50 = 70.0,
                            ProductName = "Arsenal Jersey"
                        },
                        new
                        {
                            ProductID = 2,
                            Brand = "Adidas",
                            Description = "Official Arsenal FC cap.",
                            ListPrice = 25.0,
                            Price = 20.0,
                            Price100 = 15.0,
                            Price50 = 18.0,
                            ProductName = "Arsenal Hat"
                        },
                        new
                        {
                            ProductID = 3,
                            Brand = "Adidas",
                            Description = "Official Arsenal FC scarf.",
                            ListPrice = 20.0,
                            Price = 18.0,
                            Price100 = 15.0,
                            Price50 = 17.0,
                            ProductName = "Arsenal Scarf"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
